apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:HIwX0P1n/uVDRiuLEyyNHtDLx8nfwT2I9+GxsBtbPDrU8q24bZcF81LKHDa+pRmZMJlD1BxTSG1H58O3q2DpmkENeke4hq0g/37aee1/kCByLjDb8+vNeb6vUffI,iv:V297bcjzJUxmFcj8W2k8lrRJNLvZOFGdjN64nMQh9Lg=,tag:vGLMmR8advLN+dc99qx/sw==,type:str]
    #ENC[AES256_GCM,data:x6XSvTNmott/PcYJEuguc/pgfjLE1d4PvI6s/IEoVo/RO14uCTNdSSYRd70bzp6KtSzVMrJ0NhKRYLttxJxeZqY+iVZ4OgQ8hiP/Vw4wnBrXPgdUt/1t5oJ2iCrOQuk=,iv:q/dXMfQAuBjDC8W2ME7Ez7jy8+0So5ZTiGSE3AUrNGU=,tag:BRBff3pp4C9ocoVFqRMWLg==,type:comment]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:ME02eA==,iv:StHNDSWC9HvJ8P+Ap2XTO7kXUq+S9oo2aQnU7CR/BXs=,tag:+sxwijCnRBr6qoK8bRyzrA==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:5hLu2IymLXB2NimGYhouocvOhIrYHkwj74ymWUqKWotC,iv:jZ6z12Hm/CK3fZ3ytE0i7c0nNsbt8MBOvYFpbHqhOYo=,tag:q8ZEpiq72f5IMHOxJZFYlA==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:BWkLyBNS50cDQHIGqpv5GysIfHSs1GG8oljVELqLSmGf+hI=,iv:vhq0Z280iD8C1vaPQOShnROuiiDNxVmPJ3RlsXL1HF0=,tag:yEnk64n+fksrWBGKZSExfA==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:QX5eV07iKA==,iv:ENKgPLn9d6J2vxwOXi94yy0b2XAIM9iGBzPNiW7QKmU=,tag:3phOY6i2zCvny2U6fzlOpA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ytB+iN0TzI/Wz4ipqEnmFZ0sz+y/wSWz+sv+s6wuBiLLZ32I4wHdJg==,iv:wM0u6cvC9tAg4HCWfTSVPBiS9OTB6DaOXKCs72fFo44=,tag:9AFE7RZ4BT6aSZD25ebHPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNE9xVmVEelJvSVk1dTFW
            cVQyNkRCYTBzYUZtUWRpUi9UTmhVVEdldWxBCjduYU8yOFVEQWdkQTNueHNndWFn
            bVdaSW1LbkRuUjg5bC9NclVObEpjSjQKLS0tIGdFajRGaEZ0WVFnYjAxV0dJTElo
            QWlFa29KUGhWNWl3V1prM2tvYjdVYU0KLWmEiAHVb3OQT1mv2FZR3DX1O4Z3Nsa6
            sy9adlLJwA4+a9QeUrZ+oiVcLPcnYo62kmlHwcAhBLPxz7250xuOtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T14:08:41Z"
    mac: ENC[AES256_GCM,data:aKF9Lha0eyVHsMAjJM/3cmtcaAefZxA+K9fopxO2ZFPDqg4r50+n6IrR0+CSJCj6XUyooKZ/bXi2XmFuA1o27i/kE7itlctkUSOnSzU002gCXlmJj0cq8dRaPGkm/KeOb8cfz17kN1rBKvJkVvDBXBN2I+hDDp0jdkpa+FY4GmU=,iv:HN6t6ouWVXwYx590hLpr5EK6qqhBkBPigVOzjf9hxsk=,tag:CxBnInw2WvsyV85Mptphtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4