apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:USVPcRMXCa8X0OQWWlR6MEGPuINUv2q02XmKW9yuQ1yx9gRxbQ09Boqw0Of5Z8XJ6FOPWfW6gBo7Np1GSM8qu8Y+Pm3CaYKHmQGoCu5l3wMaKCZRaOn4MU3FcPGc,iv:gH3Qwzb9kVDqZq7f9ZPueTBwzNX+EqSgWNP3nxx+/yM=,tag:c9N6NN1RskHwZzK1V9jVaw==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:MZk9ibokSzAHSrIFFSrW/uIHk8NIzZIb0FufT6Tv88YaQ0JDywcIwg==,iv:pnjXhurGLyuPz1WbTXpL28ao4w75ovH2IAEojXtfBdc=,tag:Hb7DmzDLGGxyKvvNzT3wOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWjEyRXJnRVYzZlZ1c1Nt
            Vm1uM216TFk3bEViOFdQOENpVTJtRTFDSVFFCnFWTUJzSStOUGJCYnNBelo0c0dI
            V0NMRE5qbllrc0FjbHg1bjVUTmZsUzQKLS0tIHhITVBzcnVPdk53eHNvejBicFNz
            eEJkNHgzb2p1ejRGZ2JzbnZybzVWZmsKvqLEsysyL0VgLBexZHxAoeB/CA3Gnou5
            57kVoJH+ohGqFTX66PbReRuqj0MJuFABAaA+gLBS8IIV2fJo9HpaLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T14:10:48Z"
    mac: ENC[AES256_GCM,data:TbANVxPZOUNDb56im6mrYVro4VPIazDKXO5LuD+oxt3J2IIgk/EdEdqFsGrw1Mv9nepCrgCvrbPVi4OU+1VfAlDE+k9WnAM6RcMQK4Gz7r1x+fRPviVzbuadtx/07yKd2V6LSwBXfkZsptCOf+liPaY2WHI2jnMYl2RCGpvkX7s=,iv:HKZLZ44/HboIf6XhJ3RWjjkAKEaBK41+PzoNLgi7Jpo=,tag:vv/WbYHDBWlHgfWYy8LuiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4