apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:4yTbpja2ZAal2jMgiyu4/Qpd9hPVmcWPhZPBQ7vLfX+ewSpJVw+bWf8ATXSXPiAR4qrUIjXfC6F6q2zUOr8tEN3tuVK8xFRJ/RZY1BYe+DgPgoUwhqEByB/yAk7b,iv:DfF/LqF8+AnO832WKK6+vJsMMVoC5I+duSIRvo1/I+U=,tag:BKFP353dv3EnvAm7BqiwBQ==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:zdk4XvP0vRjXbURnQ4BkDntxJyjwThspHkUsQ8QTUqXTuCucvr5WxA==,iv:wNw1zcnrfstaXXIDl0pDbNRgASAe5vfANQI+rM0Xbck=,tag:xq+W8JAVyXa9ZFPWsfKTQQ==,type:str]
    RENOVATE_GIT_PRIVATE_KEY: ENC[AES256_GCM,data:R3n2E6mX09BbnbM9R6kt5UTZlljY5+Fpfj6eGWByrqsV3ry2BOi9EHYwCdR34V9nzYM18Fn1vOOKfLAZPr+XHpZote/gkYd6AVFz/qmPRTNpRLoP0lcrjWiE5wTGufAuV5fkZXjy+ieedPKQ0oLVPPA+qeWz3NgzrxSAwaWtYbngWxx560YcoKnNELx8CbrVK1WEOg4xFRoD2sR728Tm3IURF6MDTAdPvaQQ8lejjlTGMwabqAEuux9EJONdpwEdYQAj8U4Qhs746fXNUaEGOhCfpfjSuRZNeoODnIjDWZmDoVRTw9tXtb6MlvtIFTuc3mV8QCh22hbhAN/mmXE0L+pIOTHuwJ2Q3ksz40fJiCxveLOOOaWj3oFyrgEQ7dxhgShZRl311b/YWmLa/9WEvI/g99DpgfKd49D2U82exOp6pGbn2LPNm5Ab/ghaOc5Y8IA9tMJyGjJTcMAIvrmdCPKEiV7FpEyTSU95xtJaoz1k32QoADWvULf6mcuW52ObSced0Jswyx5Kk5aoB8IzB1dTZf8/522ZbEv8,iv:02I8jgN1lBG1ZmnKWKnd4vRuBq24yrYOvhoddihJ5QE=,tag:tIElUvEIoPLfzqf/nBdqyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZME5Mc1FTWldIV1ZmMGtY
            WDZKMFlheTZTTTdXRG80d05zNms2SmUrZ0dnCm0yNHRKYVVMOVpVL0UzeVNsd25x
            VFQwaDF2RTArTzRrMXZwQ0l1UXVPRzgKLS0tIEtqRnFxR0hLVzNWK3I0RDJYR0Fn
            cElXRWdPR0ZaWUJXb0pEL0dsWFdOWmMKtqrdHzWXRjgfBPb0egJUQvxvBXkC8LKW
            AyGh/hu0XFbWA4cKjvojq5NE8iwrIzs10S9F/JnMLrhUIpAgBJdZEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T14:28:40Z"
    mac: ENC[AES256_GCM,data:BpXb+Hfw47fukBG/Xsvtx8F7dQEg/dZAM5mPfKeU7voUlsL8oHvQs+q8SahQ9Jyb16xjHF+xbh7okq+T62ZXBTNMwyElgBegET0nt3kgNv5UoPMROhza+OOuWHLLCV/JSvb+oh2BnHThzpXkRs/mXsffbqedJp/oIYwx4Fp22gE=,iv:Yep/qD6LxNA7YuruNXJFEba3WGh5VgDp0VYu4kQ5GEw=,tag:OFUFvhk9t28yeX0HEhV6hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4