apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook-url
---
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:xPSHlvuH+pCzF1CDGI2zb9+lLzoDS+r/gscjyopvWM0tEePV5kAGDlFTPDX3hNParNT5g8C4sSJgzh643uXZJBF4D29inLZS8b1Oy5uv+Eb5rla0XkV8NSvEDpCztIrlzvNQdwkIuEmXwh0c9aJYSXHZkB+p1SrVIw==,iv:HPe5MTAlnQBcVCuqjakosHe5x4TurWIn7WWXUJfVgyg=,tag:LybkwSMFPbG3eAfv97DJWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWWV2bjFGMnhSY0d0Mi8v
            eEFXOGQxRzdJUUJhcDZvd1o3L0J0Rk8xMmpjClBLQkFLRVBrd05lMkluL0tFOGY4
            OEJvdm52djYzUHBPQTFIbTMrb2MzYlkKLS0tIC8yVE5DNXJxb0RCWVB6WG9XOVZz
            UVlKbGZsZWJhbzBXbUUyRXVrd1o4dVEKsZtwN77767oU/5qgHVJS05cjrGq5ardc
            nVnvA2y8j9Tj/oCpVRqI+6fUIVsas/VID2t7VNc3Hd85oamu608p2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T16:16:07Z"
    mac: ENC[AES256_GCM,data:ztpE64Z+tlSZedWTJ4QIWGBN3ojruophjU9MsklXp62pUB5NwvPBoTxh6ol6Z1JXewuY03qSLI5PlKRcl8oF+xtuedgZQuA7XAOs1rRCaYpvncJM9CE/tOqO4CBOGXhaUYcoRpHPCDfOTGNNvp/rVgQToK6AdtxL1ECmDD8ysio=,iv:JXSgRh7cPRmrP0XpzGi4DNdMQ5syGS7Q9k6P8hM9iIQ=,tag:J1vDYOMMWQAFrUL3ZILHDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4