apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: 2
  storage:
    storageClass: longhorn
    size: 5Gi
  # Pin primary to beefy node
  affinity:
    nodeSelector:
      node-role.bach-industries/heavy: "true"
  backup:
    barmanObjectStore:
      destinationPath: s3://databases@auto/cnpg/postgres-platform
      endpointURL: https://e91592c86fc182244fa901d01efa9b35.eu.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: cnpg-r2-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-r2-secret
          key: SECRET_ACCESS_KEY
    retentionPolicy: "14d"