apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oneuptime
  namespace: oneuptime
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: status.example.com
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`status.example.com`)
      kind: Rule
      services:
        - name: oneuptime
          port: 80
      middlewares:
        - name: default-headers
          namespace: traefik
  tls:
    secretName: oneuptime-tls