apiVersion: v1
kind: Secret
metadata:
    name: oneuptime-db-creds
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:R59iz+XBOO0j,iv:EoIi+Ikl2y2uESP9MThYf0RDG90xXClrDhmDiYWCdog=,tag:nAppRAAga7BETx2aiWjbgg==,type:str]
    password: ENC[AES256_GCM,data:ogoJiQvyHTeaIjLhey+X3EES2sSjjlM1VXsE+hjWCvmn41hzRPfzy5581ef0TkNRrkXwj6qF7GIbxnjvOEeZaYXArDh3KQDY99T4lCLMh5EaE43ZBjdXkCews0TT5CAtIWXMz/F+dqZ2hKPGw1r1y2zTWm14Fz1dsHT7xXPokgU=,iv:Suxb+UesgfylI5QPhOiW1MsO739gMRQu53SxrVxFE0M=,tag:MWZWJEdESq6pfqkzdFLpFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VGJ2NEJIbkM5VTVuMUFO
            ZDNYQTRvYkFmVERIV0dhQ3M0NWVKZU81bWhNCnZrQzFPbE9VSzkzRGM1Tlk0Z2wv
            REV4Tk00NXIzbUJLaDlEVU9FOFZxUW8KLS0tIGU4bk9FbC92YUc5aHZGclpDbnpR
            eWNOdnBJZDZGUit5RForbGthUkJKeTAKfBCBTMxp2hsOEkmJFv/6NWsLbwFgIeeN
            uMbHyKM9o3ATRWbvXG1sMl4GeOOEh5UAztbeWlx1PAnVhrBGaP0gEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T11:17:27Z"
    mac: ENC[AES256_GCM,data:rxArEG1IkTlq29F3U8O1y2iY96oXqW/st9fw8YlhQm5ft7xjaWaSNhARs4pfQEA7LSOWysKBqV/XO/0eQeUyvD96Lp+m2M28dbP2njTKZj9vkzAjKaXi9oZeNioamn16/wX5BGSZhGSeQRx8/2WjlqJ/o9RDK2WSRXQOgdb4Z4I=,iv:VSDvgy89NLBAlYSBBY0SelMXk3nmNTDG7Q0GSgrMIUI=,tag:z7reBXzg+Hb072JGOL+ugA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4