apiVersion: v1
kind: Secret
metadata:
    name: minecraft-rcon
    namespace: minecraft
    labels:
        app: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:mL/8WT/2HGNP2CWLAnCHFDEEDrvrYH2qy0mZU16f+gwcBf7A9Fb9P0ZOoZJJNAAtKaUQSSX4lNzCUnvIlNlB9iCfXv6QU7omuzTyTeqZo/WcnY8IjN8aQj6N9fFMxXpe0BugCI2k4tJwrJlGk2ZkDy4K5WhbDyfR6Y+P+Cr0JZk=,iv:YhGcyaAg8sdiBAxV1HXlASOvMdigx4fY9NKFzrlVbl4=,tag:KshyqUDcupZl7WzCKTvzWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb3hLSlJmTFVnOXVYRUFy
            ak8xWXpkLzAxMXMyaVZOVVE2QzZGaTl2U1JJCnVZSVJZbnlyL1B5L0Eyd0dQekNU
            N3hWOXU1VldUY0pGLzZiZEFIRUJDMVEKLS0tIEFmRVZTWjJPZUk0NWJXNloyWWlu
            SWpvUTdNOEdPTEljVnZqdnNtMUc3V0UKwcXNYxa2cuhGdmqoyeu6W74xUVrti0wV
            lqHulmQwtI1bqJCbc+X9AU83SRRTtyJbH6C0WqjoGcRs1NEq1lGBsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T15:08:41Z"
    mac: ENC[AES256_GCM,data:2jtBHcrOovWgioVgtxkRz7jCNahyEgCMUunOe/UUzKkRR+1bGv+REXaTf0SnMG9VWHWuAu8bNknianOtRlnjh80RGv0UUJD9xgfNAeM/IMLM4wjHLHIeemYF45XmKprh8C8vjla8BMaI3+OXbqB3UNNQsi8GVZn7MXsyoNP1+eE=,iv:q0tRk8A2I1hIYBfU1Bx3mnub44MqIXeyj//5SR6mDYI=,tag:w/l4/CKKs3np1buFKbrtdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4