apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-client
    namespace: metrics
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:pBI/EXJM5J8PM5+dHeG/fly6glOG2EQMkBFcJWC8wTg=,iv:+GpJeT097NQ7e7eY8uAePteNe4ZIbcUn6IzsemMmZDk=,tag:yM8C7lwJpRtiDekJmwU7nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NWhEeUkwVjBQM1VuNkR5
            UUNrc2I1OUYvMFMwNUo3L25FeVN3cGhqd0RFCklLZ04vZFNxUFNlSko0VmhSdVQy
            YXVQRnA0ZnppcDFjZ1pvV3lMRGNhSTgKLS0tIDJiR21RelVxNUhTZlkrbWhtbWRD
            M3FsZDh3M0NRUUJiSnNlMVZZa3ZHTGsKyn4bnfcpRcdnYmbbno+ZXQGaQ2snndRS
            ifGU3soMj++adS3nlPc9hs2L9W83s0pQs1AHCBijg9SqnfyjGjYovQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T12:11:40Z"
    mac: ENC[AES256_GCM,data:QfcnK521cigaaefwlfzEvf7ZzC4nkxXIWiAeIAlXDo6EJem12aGEZHGDNxCIm7iJhyuIsazCakv+lr0R7ycnfdEWGOWSud0FWHPlsL0heuTKfzyj5/LUYm7YKSh6c5zTsAsolsNAoVlvV5QT2VQkQxAvPlul1P5qu8dbvty7BTo=,iv:GaO7NZfymhFx8H2gLjwnVzwmkYoonSIfiCSjXHTFJ2M=,tag:ESXywcCvOyDgcvv8MTR/sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4